server:
  port: 9091

spring:
  datasource:
    url: jdbc:h2:~/facility
    #url: jdbc:h2:tcp://localhost/~/jpashop1;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #        show_sql: true   SYSOUT 을 통해 찍음.
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
